# SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause

obj-$(CONFIG_RTW8723DU) += rtw8723du.o
rtw8723du-objs += main.o \
	   mac80211.o \
	   util.o \
	   debug.o \
	   tx.o \
	   rx.o \
	   mac.o \
	   phy.o \
	   coex.o \
	   efuse.o \
	   fw.o \
	   ps.o \
	   sec.o \
	   bf.o \
	   regd.o \
       sar.o \
	   rtw8822c.o rtw8822c_table.o \
	   rtw8822bu.o \
	   rtw8822b.o rtw8822b_table.o \
	   rtw8821cu.o \
	   rtw8821c.o rtw8821c_table.o \
	   rtw8814au.o \
	   rtw8814a.o rtw8814a_table.o \
	   rtw8821au.o \
	   rtw88xxa.o \
	   rtw8812a.o rtw8812a_table.o \
	   rtw8821a.o rtw8821a_table.o \
	   rtw8812au.o \
	   rtw8723x.o \
	   rtw8723du.o \
	   rtw8703b.o rtw8703b_tables.o \
	   rtw8723d.o rtw8723d_table.o \
	   wow.o \
	   usb.o \


