obj-$(CONFIG_HELLO_MODULE) += hello.o
obj-$(CONFIG_RTW8723DU) += rtw8723du.o

rtw8723du-objs := \
    rtw8723du.o \
    rtw8723d.o \
    main.o \
    usb.o  \
    util.o \
    regd.o \
    debug.o \
    fw.o \
    coex.o \
    tx.o \
    ps.o \
    phy.o \
    rx.o \
    sec.o \
    mac.o \
    sdio.o \
    wow.o \
    efuse.o \
    bf.o \
    rtw8723x.o \
    sar.o \
    rtw8723d_table.o \
    mac80211.o


